// default package
// Generated 19 ene 2024, 9:05:07 by Hibernate Tools 6.3.1.Final

/**
 * Clientes generated by hbm2java
 */
public class Clientes implements java.io.Serializable {

	private String codCliente;
	private String nombre;
	private String codRepresentante;
	private Double limiteCredito;

	public Clientes() {
	}

	public Clientes(String codCliente, String nombre, String codRepresentante, Double limiteCredito) {
		this.codCliente = codCliente;
		this.nombre = nombre;
		this.codRepresentante = codRepresentante;
		this.limiteCredito = limiteCredito;
	}

	public String getCodCliente() {
		return this.codCliente;
	}

	public void setCodCliente(String codCliente) {
		this.codCliente = codCliente;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCodRepresentante() {
		return this.codRepresentante;
	}

	public void setCodRepresentante(String codRepresentante) {
		this.codRepresentante = codRepresentante;
	}

	public Double getLimiteCredito() {
		return this.limiteCredito;
	}

	public void setLimiteCredito(Double limiteCredito) {
		this.limiteCredito = limiteCredito;
	}

}
