package galpitos;
// Generated 10 ene 2024 9:41:14 by Hibernate Tools 6.3.1.Final

/**
 * Customerdemographics generated by hbm2java
 */
public class Customerdemographics implements java.io.Serializable {

	private String customerTypeId;
	private String customerDesc;

	public Customerdemographics() {
	}

	public Customerdemographics(String customerTypeId, String customerDesc) {
		this.customerTypeId = customerTypeId;
		this.customerDesc = customerDesc;
	}

	public String getCustomerTypeId() {
		return this.customerTypeId;
	}

	public void setCustomerTypeId(String customerTypeId) {
		this.customerTypeId = customerTypeId;
	}

	public String getCustomerDesc() {
		return this.customerDesc;
	}

	public void setCustomerDesc(String customerDesc) {
		this.customerDesc = customerDesc;
	}

}
