package modelo;
// Generated 26 ene 2024 13:50:31 by Hibernate Tools 6.3.1.Final

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

	private ProductosId id;
	private String descripcion;
	private double precioCompra;
	private int existencias;

	public Productos() {
	}

	public Productos(ProductosId id, String descripcion, double precioCompra, int existencias) {
		this.id = id;
		this.descripcion = descripcion;
		this.precioCompra = precioCompra;
		this.existencias = existencias;
	}

	public ProductosId getId() {
		return this.id;
	}

	public void setId(ProductosId id) {
		this.id = id;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public double getPrecioCompra() {
		return this.precioCompra;
	}

	public void setPrecioCompra(double precioCompra) {
		this.precioCompra = precioCompra;
	}

	public int getExistencias() {
		return this.existencias;
	}

	public void setExistencias(int existencias) {
		this.existencias = existencias;
	}

}
